export const GETALLPOKEMONS='GETALLPOKEMONS';
export const SEARCHPOKEMON='SEARCHPOKEMON';
export const GETPOKEMONDETAIL='GETPOKEMONDETAIL';
export const GETALLTYPES='GETALLTYPES';
export const FILTERTYPE='FILTERTYPE';
export const FILTERORIGIN='FILTERORIGIN';
export const ALPHABETICALORDER='ALPHABETICALORDER';
export const ATACKORDER='ATACKORDER';