export const GETALLPOKEMONS='GETALLPOKEMONS';
export const RESTOREAUX='RESTOREAUX';
export const CREATEPOKEMON='CREATEPOKEMON';
export const SEARCHPOKEMON='SEARCHPOKEMON';
export const GETPOKEMONDETAIL='GETPOKEMONDETAIL';
export const DELETEDETAIL='DELETEDETAIL';
export const GETALLTYPES='GETALLTYPES';
export const FILTERTYPE='FILTERTYPE';
export const FILTERORIGIN='FILTERORIGIN';
export const ALPHABETICALORDER='ALPHABETICALORDER';
export const ATACKORDER='ATACKORDER';

//state 
export const ISFIRSTMOUNT='ISFIRSTMOUNT';

